/*
 * This file has been automatically generated by the WICED BT Designer.
 * Definitions for constants used in the device's GATT database and function
 * prototypes that can be used to send notifications
 *
 */

// hci_ble_hid_dev_db.h

#ifndef __GATT_DATABASE_H__
#define __GATT_DATABASE_H__

#define HID_REPORT_TYPE_INPUT               1
#define HID_REPORT_TYPE_OUTPUT              2
#define HID_REPORT_TYPE_FEATURE             3

#define HID_INPUT_REPORT_ID                 1
#define HID_OUTPUT_REPORT_ID                1
#define HID_INPUT_REPORT2_ID                2
#ifdef AUDIO_SUPPORT
#define HID_AUDIO_CTRL_FEATURE_REPORT_ID    0xF8    // Audio Configuration (from Host to Device)
#define HID_AUDIO_CTRL_INPUT_REPORT_ID      0xF8    // Audio Request (from Device to Host)
#define HID_AUDIO_DATA_INPUT_REPORT_ID      0xF7    // Audio Data (from Device to Host)
#endif

#define GATT_DB_ENABLE_UART                 //UART is enabled in wic file

// ***** Primary service 'Generic Attribute'
#define HDLS_GENERIC_ATTRIBUTE                                               0x0001

// ***** Primary service 'Generic Access'
#define HDLS_GENERIC_ACCESS                                                  0x0014
// ----- Characteristic 'Device Name'
#define HDLC_GENERIC_ACCESS_DEVICE_NAME                                      0x0015
#define HDLC_GENERIC_ACCESS_DEVICE_NAME_VALUE                                0x0016
// ----- Characteristic 'Appearance'
#define HDLC_GENERIC_ACCESS_APPEARANCE                                       0x0017
#define HDLC_GENERIC_ACCESS_APPEARANCE_VALUE                                 0x0018

// ***** Primary service 'Human Interface Device'
#define HDLS_HUMAN_INTERFACE_DEVICE                                          0x0028
// ----- Characteristic 'Report Map'
#define HDLC_HUMAN_INTERFACE_DEVICE_REPORT_MAP                               0x0029
#define HDLC_HUMAN_INTERFACE_DEVICE_REPORT_MAP_VALUE                         0x002A
// ----- Characteristic 'HID Information'
#define HDLC_HUMAN_INTERFACE_DEVICE_HID_INFORMATION                          0x002B
#define HDLC_HUMAN_INTERFACE_DEVICE_HID_INFORMATION_VALUE                    0x002C
// ----- Characteristic 'HID Control Point'
#define HDLC_HUMAN_INTERFACE_DEVICE_HID_CONTROL_POINT                        0x002D
#define HDLC_HUMAN_INTERFACE_DEVICE_HID_CONTROL_POINT_VALUE                  0x002E
// ----- Characteristic 'Protocol Mode'
#define HDLC_HUMAN_INTERFACE_DEVICE_PROTOCOL_MODE                            0x002F
#define HDLC_HUMAN_INTERFACE_DEVICE_PROTOCOL_MODE_VALUE                      0x0030
// ----- Characteristic 'Report'
#define HDLC_HUMAN_INTERFACE_DEVICE_REPORT_INPUT_REPORT                      0x0031
#define HDLC_HUMAN_INTERFACE_DEVICE_REPORT_INPUT_REPORT_VALUE                0x0032
// Client Configuration
#define HDLD_HUMAN_INTERFACE_DEVICE_REPORT_INPUT_REPORT_CLIENT_CONFIGURATION 0x0033
// Report Reference
#define HDLD_HUMAN_INTERFACE_DEVICE_REPORT_INPUT_REPORT_REPORT_REFERENCE     0x0034
// ----- Characteristic 'Report'
#define HDLC_HUMAN_INTERFACE_DEVICE_REPORT_OUTPUT_REPORT                     0x0035
#define HDLC_HUMAN_INTERFACE_DEVICE_REPORT_OUTPUT_REPORT_VALUE               0x0036
// Report Reference
#define HDLD_HUMAN_INTERFACE_DEVICE_REPORT_OUTPUT_REPORT_REPORT_REFERENCE    0x0037
// ----- Characteristic 'Report'
#define HDLC_HUMAN_INTERFACE_DEVICE_REPORT_INPUT_REPORT2                     0x0038
#define HDLC_HUMAN_INTERFACE_DEVICE_REPORT_INPUT_REPORT2_VALUE               0x0039
// Client Configuration
#define HDLD_HUMAN_INTERFACE_DEVICE_REPORT_INPUT_REPORT2_CLIENT_CONFIGURATION 0x003A
// Report Reference
#define HDLD_HUMAN_INTERFACE_DEVICE_REPORT_INPUT_REPORT2_REPORT_REFERENCE    0x003B

#ifdef AUDIO_SUPPORT
// ----- Characteristic 'Report' for Audio Control Feature (from Host to Device)
#define HDLC_HUMAN_INTERFACE_DEVICE_REPORT_AUDIO_CTRL_FEATURE_REPORT                0x003C
#define HDLC_HUMAN_INTERFACE_DEVICE_REPORT_AUDIO_CTRL_FEATURE_VALUE                 0x003D
// Report Reference
#define HDLD_HUMAN_INTERFACE_DEVICE_REPORT_AUDIO_CTRL_FEATURE_REPORT_REFERENCE      0x003E

// ----- Characteristic 'Report' for Audio Control Input (from Device to Host)
#define HDLC_HUMAN_INTERFACE_DEVICE_REPORT_AUDIO_CTRL_INPUT_REPORT                  0x003F
#define HDLC_HUMAN_INTERFACE_DEVICE_REPORT_AUDIO_CTRL_INPUT_VALUE                   0x0040
// Client Configuration
#define HDLD_HUMAN_INTERFACE_DEVICE_REPORT_AUDIO_CTRL_INPUT_CLIENT_CONFIGURATION    0x0041
// Report Reference
#define HDLD_HUMAN_INTERFACE_DEVICE_REPORT_AUDIO_CTRL_INPUT_REPORT_REFERENCE        0x0042

// ----- Characteristic 'Report' for Audio Data Input (from Device to Host)
#define HDLC_HUMAN_INTERFACE_DEVICE_REPORT_AUDIO_DATA_INPUT_REPORT                  0x0043
#define HDLC_HUMAN_INTERFACE_DEVICE_REPORT_AUDIO_DATA_INPUT_VALUE                   0x0044
// Client Configuration
#define HDLD_HUMAN_INTERFACE_DEVICE_REPORT_AUDIO_DATA_INPUT_CLIENT_CONFIGURATION    0x0045
// Report Reference
#define HDLD_HUMAN_INTERFACE_DEVICE_REPORT_AUDIO_DATA_INPUT_REPORT_REFERENCE        0x0046
#endif

// ***** Primary service 'Immediate Alert'
#define HDLS_IMMEDIATE_ALERT                                                 0x0050
// ----- Characteristic 'Alert Level'
#define HDLC_IMMEDIATE_ALERT_ALERT_LEVEL                                     0x0051
#define HDLC_IMMEDIATE_ALERT_ALERT_LEVEL_VALUE                               0x0052

// ***** Primary service 'Battery Service'
#define HDLS_BATTERY_SERVICE                                                 0x0060
// ----- Characteristic 'Battery Level'
#define HDLC_BATTERY_SERVICE_BATTERY_LEVEL                                   0x0061
#define HDLC_BATTERY_SERVICE_BATTERY_LEVEL_VALUE                             0x0062

// ***** Primary service 'Device Information'
#define HDLS_DEVICE_INFORMATION                                              0x0070
// ----- Characteristic 'PnP ID'
#define HDLC_DEVICE_INFORMATION_PNP_ID                                       0x0071
#define HDLC_DEVICE_INFORMATION_PNP_ID_VALUE                                 0x0072

// External Lookup Table Entry
typedef struct
{
    uint16_t handle;
    uint16_t max_len;
    uint8_t  *p_data;
} gatt_db_lookup_table;

// External definitions
extern const uint8_t  gatt_database[];
extern const uint16_t gatt_database_len;
extern gatt_db_lookup_table hci_ble_hid_dev_gatt_db_ext_attr_tbl[];
extern const uint16_t hci_ble_hid_dev_gatt_db_ext_attr_tbl_size;
extern uint8_t BT_LOCAL_NAME[];
extern const uint16_t BT_LOCAL_NAME_CAPACITY;

extern uint8_t hci_ble_hid_dev_human_interface_device_hid_control_point[];
extern uint8_t hci_ble_hid_dev_human_interface_device_protocol_mode[];
extern uint8_t hci_ble_hid_dev_human_interface_device_report_input_report_report_reference[];
extern uint8_t hci_ble_hid_dev_human_interface_device_report_output_report_report_reference[];
extern uint8_t hci_ble_hid_dev_human_interface_device_report_output_report[];
extern uint8_t hci_ble_hid_dev_human_interface_device_report_input_report2_report_reference[];
extern uint8_t hci_ble_hid_dev_immediate_alert_alert_level[];
extern uint8_t hci_ble_hid_dev_battery_service_battery_level[];

#endif /* __GATT_DATABASE_H__ */
