/*
 * This file has been automatically generated by the WICED BT Designer.
 * BLE device's GATT database, device configuration.
 *
 */

// hci_ble_hid_dev_db.c

#include "wiced_bt_sdp_defs.h"
#include "wiced.h"
#include "wiced_gki.h"
#include "wiced_bt_dev.h"
#include "wiced_bt_ble.h"
#include "wiced_bt_uuid.h"
#include "wiced_bt_gatt.h"
#include "wiced_bt_cfg.h"
#include "wiced_hal_gpio.h"
#include "wiced_hal_nvram.h"
#if ( defined(CYW20706A2) || defined(CYW20719B1) || defined(CYW20719B0) || defined(CYW20721B1) || defined(CYW20735B0) || defined(CYW43012C0) )
#include "wiced_bt_app_common.h"
#include "wiced_bt_app_hal_common.h"
#endif
#include "wiced_result.h"
#include "hci_ble_hid_dev_db.h"

/*************************************************************************************
** GATT server definitions
*************************************************************************************/

const UINT8 gatt_database[] = // Define GATT database
{
    /* Primary Service 'Generic Attribute' */
    PRIMARY_SERVICE_UUID16 (HDLS_GENERIC_ATTRIBUTE, UUID_SERVICE_GATT),

    /* Primary Service 'Generic Access' */
    PRIMARY_SERVICE_UUID16 (HDLS_GENERIC_ACCESS, UUID_SERVICE_GAP),

        /* Characteristic 'Device Name' */
        CHARACTERISTIC_UUID16 (HDLC_GENERIC_ACCESS_DEVICE_NAME, HDLC_GENERIC_ACCESS_DEVICE_NAME_VALUE,
            UUID_CHARACTERISTIC_DEVICE_NAME, LEGATTDB_CHAR_PROP_READ,
            LEGATTDB_PERM_READABLE),

        /* Characteristic 'Appearance' */
        CHARACTERISTIC_UUID16 (HDLC_GENERIC_ACCESS_APPEARANCE, HDLC_GENERIC_ACCESS_APPEARANCE_VALUE,
            UUID_CHARACTERISTIC_APPEARANCE, LEGATTDB_CHAR_PROP_READ,
            LEGATTDB_PERM_READABLE),

    /* Primary Service 'Human Interface Device' */
    PRIMARY_SERVICE_UUID16 (HDLS_HUMAN_INTERFACE_DEVICE, UUID_SERVICE_HID),

        /* Characteristic 'Report Map' */
        CHARACTERISTIC_UUID16 (HDLC_HUMAN_INTERFACE_DEVICE_REPORT_MAP, HDLC_HUMAN_INTERFACE_DEVICE_REPORT_MAP_VALUE,
            UUID_CHARACTERISTIC_REPORT_MAP, LEGATTDB_CHAR_PROP_READ,
            LEGATTDB_PERM_READABLE),

        /* Characteristic 'HID Information' */
        CHARACTERISTIC_UUID16 (HDLC_HUMAN_INTERFACE_DEVICE_HID_INFORMATION, HDLC_HUMAN_INTERFACE_DEVICE_HID_INFORMATION_VALUE,
            UUID_CHARACTERISTIC_HID_INFORMATION, LEGATTDB_CHAR_PROP_READ,
            LEGATTDB_PERM_READABLE),

        /* Characteristic 'HID Control Point' */
        CHARACTERISTIC_UUID16_WRITABLE (HDLC_HUMAN_INTERFACE_DEVICE_HID_CONTROL_POINT, HDLC_HUMAN_INTERFACE_DEVICE_HID_CONTROL_POINT_VALUE,
            UUID_CHARACTERISTIC_HID_CONTROL_POINT, LEGATTDB_CHAR_PROP_WRITE_NO_RESPONSE,
            LEGATTDB_PERM_WRITE_CMD),

        /* Characteristic 'Protocol Mode' */
        CHARACTERISTIC_UUID16_WRITABLE (HDLC_HUMAN_INTERFACE_DEVICE_PROTOCOL_MODE, HDLC_HUMAN_INTERFACE_DEVICE_PROTOCOL_MODE_VALUE,
            UUID_CHARACTERISTIC_PROTOCOL_MODE, LEGATTDB_CHAR_PROP_READ | LEGATTDB_CHAR_PROP_WRITE_NO_RESPONSE | LEGATTDB_CHAR_PROP_WRITE,
            LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_CMD | LEGATTDB_PERM_WRITE_REQ),

        /* Characteristic 'Input Report' */
        CHARACTERISTIC_UUID16 (HDLC_HUMAN_INTERFACE_DEVICE_REPORT_INPUT_REPORT, HDLC_HUMAN_INTERFACE_DEVICE_REPORT_INPUT_REPORT_VALUE,
            UUID_CHARACTERISTIC_REPORT, LEGATTDB_CHAR_PROP_READ | LEGATTDB_CHAR_PROP_NOTIFY,
            LEGATTDB_PERM_READABLE),

            /* Client Characteristic Configuration Descriptor */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (HDLD_HUMAN_INTERFACE_DEVICE_REPORT_INPUT_REPORT_CLIENT_CONFIGURATION,
                UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION, LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_REQ | LEGATTDB_PERM_AUTH_WRITABLE),

            /* Report Reference Descriptor */
            CHAR_DESCRIPTOR_UUID16 (HDLD_HUMAN_INTERFACE_DEVICE_REPORT_INPUT_REPORT_REPORT_REFERENCE,
                UUID_DESCRIPTOR_REPORT_REFERENCE, LEGATTDB_PERM_READABLE),

        /* Characteristic 'Output Report' */
        CHARACTERISTIC_UUID16_WRITABLE (HDLC_HUMAN_INTERFACE_DEVICE_REPORT_OUTPUT_REPORT, HDLC_HUMAN_INTERFACE_DEVICE_REPORT_OUTPUT_REPORT_VALUE,
            UUID_CHARACTERISTIC_REPORT, LEGATTDB_CHAR_PROP_READ | LEGATTDB_CHAR_PROP_WRITE_NO_RESPONSE | LEGATTDB_CHAR_PROP_WRITE,
            LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_CMD | LEGATTDB_PERM_WRITE_REQ),

            /* Report Reference Descriptor */
            CHAR_DESCRIPTOR_UUID16 (HDLD_HUMAN_INTERFACE_DEVICE_REPORT_OUTPUT_REPORT_REPORT_REFERENCE,
                UUID_DESCRIPTOR_REPORT_REFERENCE, LEGATTDB_PERM_READABLE),

        /* Characteristic 'Input Report 2' */
        CHARACTERISTIC_UUID16 (HDLC_HUMAN_INTERFACE_DEVICE_REPORT_INPUT_REPORT2, HDLC_HUMAN_INTERFACE_DEVICE_REPORT_INPUT_REPORT2_VALUE,
            UUID_CHARACTERISTIC_REPORT, LEGATTDB_CHAR_PROP_READ | LEGATTDB_CHAR_PROP_NOTIFY,
            LEGATTDB_PERM_READABLE),

            /* Client Characteristic Configuration Descriptor */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (HDLD_HUMAN_INTERFACE_DEVICE_REPORT_INPUT_REPORT2_CLIENT_CONFIGURATION,
                UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION, LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_REQ | LEGATTDB_PERM_AUTH_WRITABLE),

            /* Report Reference Descriptor */
            CHAR_DESCRIPTOR_UUID16 (HDLD_HUMAN_INTERFACE_DEVICE_REPORT_INPUT_REPORT2_REPORT_REFERENCE,
                UUID_DESCRIPTOR_REPORT_REFERENCE, LEGATTDB_PERM_READABLE),

#ifdef AUDIO_SUPPORT
        /* Characteristic Audio Control 'Report' (Feature) */
        CHARACTERISTIC_UUID16_WRITABLE (HDLC_HUMAN_INTERFACE_DEVICE_REPORT_AUDIO_CTRL_FEATURE_REPORT, HDLC_HUMAN_INTERFACE_DEVICE_REPORT_AUDIO_CTRL_FEATURE_VALUE,
            UUID_CHARACTERISTIC_REPORT, LEGATTDB_CHAR_PROP_READ | LEGATTDB_CHAR_PROP_WRITE_NO_RESPONSE | LEGATTDB_CHAR_PROP_WRITE,
            LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_CMD | LEGATTDB_PERM_WRITE_REQ),

            /* Report Reference Descriptor */
            CHAR_DESCRIPTOR_UUID16 (HDLD_HUMAN_INTERFACE_DEVICE_REPORT_AUDIO_CTRL_FEATURE_REPORT_REFERENCE,
                UUID_DESCRIPTOR_REPORT_REFERENCE, LEGATTDB_PERM_READABLE),

        /* Characteristic Audio Control 'Report' (Input) */
        CHARACTERISTIC_UUID16 (HDLC_HUMAN_INTERFACE_DEVICE_REPORT_AUDIO_CTRL_INPUT_REPORT, HDLC_HUMAN_INTERFACE_DEVICE_REPORT_AUDIO_CTRL_INPUT_VALUE,
            UUID_CHARACTERISTIC_REPORT, LEGATTDB_CHAR_PROP_READ | LEGATTDB_CHAR_PROP_NOTIFY,
            LEGATTDB_PERM_READABLE),

            /* Client Characteristic Configuration Descriptor */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (HDLD_HUMAN_INTERFACE_DEVICE_REPORT_AUDIO_CTRL_INPUT_CLIENT_CONFIGURATION,
                UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION, LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_REQ),

            /* Report Reference Descriptor */
            CHAR_DESCRIPTOR_UUID16 (HDLD_HUMAN_INTERFACE_DEVICE_REPORT_AUDIO_CTRL_INPUT_REPORT_REFERENCE,
                UUID_DESCRIPTOR_REPORT_REFERENCE, LEGATTDB_PERM_READABLE),

        /* Characteristic Audio Data 'Report' (Input) */
        CHARACTERISTIC_UUID16 (HDLC_HUMAN_INTERFACE_DEVICE_REPORT_AUDIO_DATA_INPUT_REPORT, HDLC_HUMAN_INTERFACE_DEVICE_REPORT_AUDIO_DATA_INPUT_VALUE,
            UUID_CHARACTERISTIC_REPORT, LEGATTDB_CHAR_PROP_READ | LEGATTDB_CHAR_PROP_NOTIFY,
            LEGATTDB_PERM_READABLE),

            /* Client Characteristic Configuration Descriptor */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (HDLD_HUMAN_INTERFACE_DEVICE_REPORT_AUDIO_DATA_INPUT_CLIENT_CONFIGURATION,
                UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION, LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_REQ),

            /* Report Reference Descriptor */
            CHAR_DESCRIPTOR_UUID16 (HDLD_HUMAN_INTERFACE_DEVICE_REPORT_AUDIO_DATA_INPUT_REPORT_REFERENCE,
                UUID_DESCRIPTOR_REPORT_REFERENCE, LEGATTDB_PERM_READABLE),

#endif

    /* Primary Service 'Immediate Alert' */
    PRIMARY_SERVICE_UUID16 (HDLS_IMMEDIATE_ALERT, UUID_SERVICE_IMMEDIATE_ALERT),

        /* Characteristic 'Alert Level' */
        CHARACTERISTIC_UUID16_WRITABLE (HDLC_IMMEDIATE_ALERT_ALERT_LEVEL, HDLC_IMMEDIATE_ALERT_ALERT_LEVEL_VALUE,
            UUID_CHARACTERISTIC_ALERT_LEVEL, LEGATTDB_CHAR_PROP_WRITE_NO_RESPONSE,
            LEGATTDB_PERM_WRITE_CMD),

    /* Primary Service 'Battery Service' */
    PRIMARY_SERVICE_UUID16 (HDLS_BATTERY_SERVICE, UUID_SERVICE_BATTERY),

        /* Characteristic 'Battery Level' */
        CHARACTERISTIC_UUID16 (HDLC_BATTERY_SERVICE_BATTERY_LEVEL, HDLC_BATTERY_SERVICE_BATTERY_LEVEL_VALUE,
            UUID_CHARACTERISTIC_BATTERY_LEVEL, LEGATTDB_CHAR_PROP_READ,
            LEGATTDB_PERM_READABLE),

    /* Primary Service 'Device Information' */
    PRIMARY_SERVICE_UUID16 (HDLS_DEVICE_INFORMATION, UUID_SERVICE_DEVICE_INFORMATION),

        /* Characteristic 'PnP ID' */
        CHARACTERISTIC_UUID16 (HDLC_DEVICE_INFORMATION_PNP_ID, HDLC_DEVICE_INFORMATION_PNP_ID_VALUE,
            UUID_CHARACTERISTIC_PNP_ID, LEGATTDB_CHAR_PROP_READ,
            LEGATTDB_PERM_READABLE),

};
// Length of the GATT database
const UINT16 gatt_database_len = sizeof(gatt_database);

uint8_t hci_ble_hid_dev_generic_access_device_name[]                                      = {'h','c','i','_','b','l','e','_','h','i','d','_','d','e','v','i','c','e'};
uint8_t hci_ble_hid_dev_generic_access_appearance[]                                       = {BIT16_TO_8(APPEARANCE_GENERIC_HID_DEVICE)};
uint8_t hci_ble_hid_dev_human_interface_device_report_map[]                               = {
    // STD_KB_REPORT_ID
    // Input Report, 8 bytes
    // 1st byte:Keyboard LeftControl/Keyboard Right GUI
    // 2nd byte:Constant, 3rd ~ 6th: keycode
    // Output Report, 1 byte: LED control
    0x05 , 0x01,                    // USAGE_PAGE (Generic Desktop)
    0x09 , 0x06,                    // USAGE (Keyboard)
    0xA1 , 0x01,                    // COLLECTION (Application)
    0x85 , 0x01,                    //    REPORT_ID (1)
    0x75 , 0x01,                    //    REPORT_SIZE (1)
    0x95 , 0x08,                    //    REPORT_COUNT (8)
    0x05 , 0x07,                    //    USAGE_PAGE (Keyboard)
    0x19 , 0xE0,                    //    USAGE_MINIMUM (Keyboard LeftControl)
    0x29 , 0xE7,                    //    USAGE_MAXIMUM (Keyboard Right GUI)
    0x15 , 0x00,                    //    LOGICAL_MINIMUM (0)
    0x25 , 0x01,                    //    LOGICAL_MAXIMUM (1)
    0x81 , 0x02,                    //    INPUT (Data,Var,Abs)
    0x95 , 0x01,                    //    REPORT_COUNT (1)
    0x75 , 0x08,                    //    REPORT_SIZE (8)
    0x81 , 0x03,                    //    INPUT (Cnst,Var,Abs)
    0x95 , 0x05,                    //    REPORT_COUNT (5)
    0x75 , 0x01,                    //    REPORT_SIZE (1)
    0x05 , 0x08,                    //    USAGE_PAGE (LEDs)
    0x19 , 0x01,                    //    USAGE_MINIMUM (Num Lock)
    0x29 , 0x05,                    //    USAGE_MAXIMUM (Kana)
    0x91 , 0x02,                    //    OUTPUT (Data,Var,Abs)
    0x95 , 0x01,                    //    REPORT_COUNT (1)
    0x75 , 0x03,                    //    REPORT_SIZE (3)
    0x91 , 0x03,                    //    OUTPUT (Cnst,Var,Abs)
    0x95 , 0x06,                    //    REPORT_COUNT (6)
    0x75 , 0x08,                    //    REPORT_SIZE (8)
    0x15 , 0x00,                    //    LOGICAL_MINIMUM (0)
    0x26 , 0xFF , 0x00,             //    LOGICAL_MAXIMUM (255)
    0x05 , 0x07,                    //    USAGE_PAGE (Keyboard)
    0x19 , 0x00,                    //    USAGE_MINIMUM (Reserved (no event indicated))
    0x29 , 0xFF,                    //    USAGE_MAXIMUM (Reserved (no event indicated))
    0x81 , 0x00,                    //    INPUT (Data,Ary,Abs)
    0xC0,                           // END_COLLECTION
    0x05, 0x0C,                     // USAGE_PAGE (Consumer Devices)
    0x09, 0x01,                     // USAGE (Consumer Control)
    0xA1, 0x01,                     // COLLECTION (Application)
    0x85, 0x02,                     //      Report ID (2)
    0x75, 0x10,                     //      REPORT_SIZE (10)
    0x95, 0x02,                     //      REPORT_COUNT (2)
    0x15, 0x01,                     //      LOGICAL_MINIMUM (1)
    0x26, 0x8c, 0x02,               //      LOGICAL_MAXIMUM (28c)
    0x19, 0x01,                     //      USAGE_MINIMUM (Button 1)
    0x2a, 0x8c, 0x02,               //      USAGE_MAXIMUM (Button 28c)
    0x81, 0x60,                     //      INPUT (data, array, abs)
    0xc0,                           // END COLLECTION
};

uint8_t hci_ble_hid_dev_human_interface_device_hid_information[]                           = {0x11,0x01,0x00,0x00};  // Version 1.11, Not localized, Cannot remote wake, not normally connectable
uint8_t hci_ble_hid_dev_human_interface_device_hid_control_point[]                         = {0xff};
uint8_t hci_ble_hid_dev_human_interface_device_protocol_mode[]                             = {0x01};
//uint8_t hci_ble_hid_dev_human_interface_device_report_input_report[]                       = {0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00};
//uint8_t hci_ble_hid_dev_human_interface_device_report_input_report_client_configuration[]  = {BIT16_TO_8(GATT_CLIENT_CONFIG_NONE)};
uint8_t hci_ble_hid_dev_human_interface_device_report_input_report_report_reference[]      = {HID_INPUT_REPORT_ID,HID_REPORT_TYPE_INPUT};
uint8_t hci_ble_hid_dev_human_interface_device_report_output_report[]                      = {0x00};
uint8_t hci_ble_hid_dev_human_interface_device_report_output_report_report_reference[]     = {HID_OUTPUT_REPORT_ID,HID_REPORT_TYPE_OUTPUT};
//uint8_t hci_ble_hid_dev_human_interface_device_report_input_report2[]                      = {0x00,0x00,0x00,0x00};
//uint8_t hci_ble_hid_dev_human_interface_device_report_input_report2_client_configuration[] = {BIT16_TO_8(GATT_CLIENT_CONFIG_NONE)};
uint8_t hci_ble_hid_dev_human_interface_device_report_input_report2_report_reference[]     = {HID_INPUT_REPORT2_ID,HID_REPORT_TYPE_INPUT};
#ifdef AUDIO_SUPPORT
uint8_t hci_ble_hid_dev_audio_ctrl_feature_report_reference[]     = {HID_AUDIO_CTRL_FEATURE_REPORT_ID, HID_REPORT_TYPE_FEATURE};
uint8_t hci_ble_hid_dev_audio_ctrl_input_report_reference[]     = {HID_AUDIO_CTRL_INPUT_REPORT_ID, HID_REPORT_TYPE_INPUT};
uint8_t hci_ble_hid_dev_audio_data_input_report_reference[]     = {HID_AUDIO_DATA_INPUT_REPORT_ID, HID_REPORT_TYPE_INPUT};
#endif
uint8_t hci_ble_hid_dev_immediate_alert_alert_level[]                                      = {0x02};
uint8_t hci_ble_hid_dev_battery_service_battery_level[]                                    = {70};
uint8_t hci_ble_hid_dev_device_information_pnp_id[]                                        = {0x02,0x5c,0x0a,0x20,0x20,0x01,0x00};

/* GATT attribute lookup table                                */
/* (attributes externally referenced by GATT server database) */
gatt_db_lookup_table hci_ble_hid_dev_gatt_db_ext_attr_tbl[] =
{
    /* { attribute handle,                                                  maxlen,                                             attribute data } */
    {HDLC_GENERIC_ACCESS_DEVICE_NAME_VALUE,                                 sizeof(hci_ble_hid_dev_generic_access_device_name), hci_ble_hid_dev_generic_access_device_name},
    {HDLC_GENERIC_ACCESS_APPEARANCE_VALUE,                                  2,                                                  hci_ble_hid_dev_generic_access_appearance},
    {HDLC_HUMAN_INTERFACE_DEVICE_REPORT_MAP_VALUE,                          sizeof(hci_ble_hid_dev_human_interface_device_report_map), hci_ble_hid_dev_human_interface_device_report_map},
    {HDLC_HUMAN_INTERFACE_DEVICE_HID_INFORMATION_VALUE,                     4,                                                  hci_ble_hid_dev_human_interface_device_hid_information},
    {HDLC_HUMAN_INTERFACE_DEVICE_HID_CONTROL_POINT_VALUE,                   1,                                                  hci_ble_hid_dev_human_interface_device_hid_control_point},
    {HDLC_HUMAN_INTERFACE_DEVICE_PROTOCOL_MODE_VALUE,                       1,                                                  hci_ble_hid_dev_human_interface_device_protocol_mode},
    {HDLD_HUMAN_INTERFACE_DEVICE_REPORT_INPUT_REPORT_REPORT_REFERENCE,      2,                                                  hci_ble_hid_dev_human_interface_device_report_input_report_report_reference},
    {HDLC_HUMAN_INTERFACE_DEVICE_REPORT_OUTPUT_REPORT_VALUE,                1,                                                  hci_ble_hid_dev_human_interface_device_report_output_report},
    {HDLD_HUMAN_INTERFACE_DEVICE_REPORT_OUTPUT_REPORT_REPORT_REFERENCE,     2,                                                  hci_ble_hid_dev_human_interface_device_report_output_report_report_reference},
    {HDLD_HUMAN_INTERFACE_DEVICE_REPORT_INPUT_REPORT2_REPORT_REFERENCE,     2,                                                  hci_ble_hid_dev_human_interface_device_report_input_report2_report_reference},
#ifdef AUDIO_SUPPORT
    {HDLD_HUMAN_INTERFACE_DEVICE_REPORT_AUDIO_CTRL_FEATURE_REPORT_REFERENCE,sizeof(hci_ble_hid_dev_audio_ctrl_feature_report_reference), hci_ble_hid_dev_audio_ctrl_feature_report_reference},
    {HDLD_HUMAN_INTERFACE_DEVICE_REPORT_AUDIO_CTRL_INPUT_REPORT_REFERENCE,  sizeof(hci_ble_hid_dev_audio_ctrl_input_report_reference), hci_ble_hid_dev_audio_ctrl_input_report_reference},
    {HDLD_HUMAN_INTERFACE_DEVICE_REPORT_AUDIO_DATA_INPUT_REPORT_REFERENCE,  sizeof(hci_ble_hid_dev_audio_data_input_report_reference), hci_ble_hid_dev_audio_data_input_report_reference},
#endif
    {HDLC_IMMEDIATE_ALERT_ALERT_LEVEL_VALUE,                                1,                                                  hci_ble_hid_dev_immediate_alert_alert_level},
    {HDLC_BATTERY_SERVICE_BATTERY_LEVEL_VALUE,                              1,                                                  hci_ble_hid_dev_battery_service_battery_level},
    {HDLC_DEVICE_INFORMATION_PNP_ID_VALUE,                                  7,                                                  hci_ble_hid_dev_device_information_pnp_id},
};

const uint16_t hci_ble_hid_dev_gatt_db_ext_attr_tbl_size = ( sizeof ( hci_ble_hid_dev_gatt_db_ext_attr_tbl ) / sizeof ( gatt_db_lookup_table ) );
