/*
 * This file has been automatically generated by the WICED Smart Ready Designer.
 * Definitions for constants used in the device's GATT database and function
 * prototypes.
 *
 */

// watch_db.h

#ifndef __GATT_DATABASE_H__
#define __GATT_DATABASE_H__

#include <stdint.h>
#include "wiced_app.h"

#define __UUID_SERIAL_GATT_SERVICE        0x7e, 0x60, 0xfa, 0xf2, 0xbe, 0x7e, 0x3b, 0xa6, 0xe0, 0x47, 0x9d, 0x05, 0xb2, 0x93, 0x52, 0x69
#define __UUID_SERIAL_GATT_SERIAL_DATA    0x8b, 0x5e, 0xfe, 0x3c, 0x2d, 0x90, 0x27, 0x87, 0xbc, 0x42, 0x00, 0xef, 0xe4, 0x46, 0x41, 0x61

// ***** Primary Service 'Generic Attribute'
#define HDLS_GENERIC_ATTRIBUTE                                                 0x0001

// ***** Primary Service 'Generic Access'
#define HDLS_GENERIC_ACCESS                                                    0x0014
// ----- Characteristic 'Device Name'
#define HDLC_GENERIC_ACCESS_DEVICE_NAME                                        0x0015
#define HDLC_GENERIC_ACCESS_DEVICE_NAME_VALUE                                  0x0016
// ----- Characteristic 'Appearance'
#define HDLC_GENERIC_ACCESS_APPEARANCE                                         0x0017
#define HDLC_GENERIC_ACCESS_APPEARANCE_VALUE                                   0x0018

// ***** Primary Service 'serial_gatt'
#define HDLS_SERIAL_GATT                                                       0x0028
// ----- Characteristic 'serial_data'
#define HDLC_SERIAL_GATT_SERIAL_DATA                                           0x0029
#define HDLC_SERIAL_GATT_SERIAL_DATA_VALUE                                     0x002A
// ===== Descriptor 'Client Configuration'
#define HDLD_SERIAL_GATT_SERIAL_DATA_CLIENT_CONFIGURATION                      0x002B

// ***** Primary Service 'Battery Service'
#define HDLS_BATTERY_SERVICE                                                   0x0070
// ----- Characteristic 'Battery Level'
#define HDLC_BATTERY_SERVICE_BATTERY_LEVEL                                     0x0071
#define HDLC_BATTERY_SERVICE_BATTERY_LEVEL_VALUE                               0x0072

// ***** Primary Service 'Device Information'
#define HDLS_DEVICE_INFORMATION                                                0x0080
// ----- Characteristic 'PnP ID'
#define HDLC_DEVICE_INFORMATION_PNP_ID                                         0x0081
#define HDLC_DEVICE_INFORMATION_PNP_ID_VALUE                                   0x0082
// ----- Characteristic 'Manufacturer Name String'
#define HDLC_DEVICE_INFORMATION_MANUFACTURER_NAME_STRING                       0x0083
#define HDLC_DEVICE_INFORMATION_MANUFACTURER_NAME_STRING_VALUE                 0x0084
// ----- Characteristic 'Model Number String'
#define HDLC_DEVICE_INFORMATION_MODEL_NUMBER_STRING                            0x0085
#define HDLC_DEVICE_INFORMATION_MODEL_NUMBER_STRING_VALUE                      0x0086
// ----- Characteristic 'Firmware Revision String'
#define HDLC_DEVICE_INFORMATION_FIRMWARE_REVISION_STRING                       0x0087
#define HDLC_DEVICE_INFORMATION_FIRMWARE_REVISION_STRING_VALUE                 0x0088
// ----- Characteristic 'Software Revision String'
#define HDLC_DEVICE_INFORMATION_SOFTWARE_REVISION_STRING                       0x0089
#define HDLC_DEVICE_INFORMATION_SOFTWARE_REVISION_STRING_VALUE                 0x008A

// External Lookup Table Entry
typedef struct
{
    uint16_t handle;
    uint16_t max_len;
    uint16_t cur_len;
    uint8_t  *p_data;
} gatt_db_lookup_table;

// External definitions

extern const uint8_t gatt_server_db[];
extern const uint16_t gatt_server_db_len;

extern const uint8_t gatt_server_db_appearance[];
extern const uint16_t gatt_server_db_appearance_len;

extern const uint8_t gatt_server_db_device_name[];
extern const uint16_t gatt_server_db_device_name_len;

extern const uint16_t watch_gatt_db_ext_attr_tbl_size;
extern gatt_db_lookup_table watch_gatt_db_ext_attr_tbl[];

extern uint8_t watch_human_interface_device_hid_information[];
extern uint8_t watch_human_interface_device_hid_control_point[];
extern uint8_t watch_human_interface_device_protocol_mode[];
extern uint8_t watch_human_interface_device_report_input_report[];
extern uint8_t watch_human_interface_device_report_input_report_client_configuration[];
extern uint8_t watch_human_interface_device_report_input_report_report_reference[];
extern uint8_t watch_human_interface_device_report_output_report[];
extern uint8_t watch_human_interface_device_report_output_report_report_reference[];
extern uint8_t watch_human_interface_device_report_input_report_2[];
extern uint8_t watch_human_interface_device_report_input_report_2_client_configuration[];
extern uint8_t watch_human_interface_device_report_input_report_2_report_reference[];
extern uint8_t watch_link_loss_alert_level[];
extern uint8_t watch_tx_power_tx_power_level[];
extern uint8_t watch_battery_service_battery_level[];
extern uint8_t watch_device_information_pnp_id[];

#endif /* __GATT_DATABASE_H__ */
