/*
 * This file has been automatically generated by the WICED Embedded Designer.
 * Definitions for constants used in the device's GATT database and function
 * prototypes.
 *
 */

#include <stdint.h>
#include "wiced.h"
#include "wiced_bt_ble.h"
#include "wiced_bt_gatt.h"
#include "wiced_app.h"
#include "wiced_timer.h"

#ifndef SERIAL_GATT_SERVICE_H
#define SERIAL_GATT_SERVICE_H

/*
#ifdef _WIN32
static const GUID  GUID_SERIAL_GATT_SERVICE = { 0x695293b2, 0x059d, 0x47e0, { 0xa6, 0x3b, 0x7e, 0xbe, 0xf2, 0xfa, 0x60, 0x7e } };
#endif
*/
#define __UUID_SERIAL_GATT_SERVICE                          0x7e, 0x60, 0xfa, 0xf2, 0xbe, 0x7e, 0x3b, 0xa6, 0xe0, 0x47, 0x9d, 0x05, 0xb2, 0x93, 0x52, 0x69

/*
#ifdef _WIN32
static const GUID  GUID_SERIAL_GATT_SERIAL_DATA = { 0x614146e4, 0xef00, 0x42bc, { 0x87, 0x27, 0x90, 0x2d, 0x3c, 0xfe, 0x5e, 0x8b } };
#endif
*/
#define __UUID_SERIAL_GATT_SERIAL_DATA                      0x8b, 0x5e, 0xfe, 0x3c, 0x2d, 0x90, 0x27, 0x87, 0xbc, 0x42, 0x00, 0xef, 0xe4, 0x46, 0x41, 0x61

// Protocol definitions
#define SERIAL_GATT_FLAGS_CREDIT_FIELD_PRESENT              0x01
#define SERIAL_GATT_FLAGS_MTU_FIELD_PRESENT                 0x02
#define SERIAL_GATT_FLAGS_DATA_FIELD_PRESENT                0x04

#define SERIAL_GATT_MAX_CREDITS                             255
#define SERIAL_GATT_MTU                                     23

void serial_gatt_service_connection_up(wiced_bt_gatt_connection_status_t *p_conn_status);
void serial_gatt_service_connection_down(wiced_bt_gatt_connection_status_t *p_conn_status);
wiced_bt_gatt_status_t serial_gatt_service_write_handler(uint16_t conn_id, wiced_bt_gatt_write_t *p_write_req);
wiced_bt_gatt_status_t serial_gatt_service_read_handler(uint16_t conn_id, wiced_bt_gatt_read_t *p_read_req);
wiced_bt_gatt_status_t serial_gatt_service_mtu_handler(uint16_t conn_id, uint16_t mtu);

#endif /* SERIAL_GATT_SERVICE_H */
